percona/pmm-server

- Dockerfile
- import-dashboards.py
- supervisord.conf
ticket https://jira.percona.com/browse/PMM-536
root of the issue - it is needed to wait some time for the other transaction to finish.
So I added [PRAGMA busy_timeout](https://www.sqlite.org/pragma.html#pragma_busy_timeout) before "REPLACE INTO" call.
> wait some time for the other transaction to finish

- Dockerfile
See https://github.com/github/orchestrator/releases
> Upgrade Orchestrator to 2.0.2

- playbook-init.yml
- supervisord.conf
```
mysql> SELECT PASSWORD('pmm-managed');
+-------------------------------------------+
| PASSWORD('pmm-managed')                   |
+-------------------------------------------+
| *816FFB19BC44AC2749D546E48FA0DF957EDB2C5A |
+-------------------------------------------+
1 row in set (0.13 sec)
```
> PMM-1717 Create pmm-managed database and user.

- nginx.conf
Before merging that let's decide if we want it for 1.5.3 or 1.6.0.
> PMM-1874 Increase proxy read timeout.

- prometheus.yml
Set scrape_interval and scrape_timeout for each standard Prometheus job explicitly. Set global values to Prometheus defaults.
> PMM-1712 Change scrape intervals.

- password-page/src/app/success-page/success-page.component.html
https://jira.percona.com/browse/PMM-2341
> PMM-2341 Fix typo on OVF password page

- prometheus.yml
https://jira.percona.com/browse/PMM-2997
> PMM-2997 Updated remote_read to point on new path.

- nginx-ssl.conf
> Remove TLS 1.0

- password-page/package-lock.json
https://jira.percona.com/browse/PMM-3413
> PMM-3413 Fix vulnerability

- nginx.conf
Both `/logs.zip` (2.x variant) and `/managed/logs.zip` (deprecated 1.x variant) should work.
> PMM-3685 Add logs.zip endpoints.

- supervisord.conf
Fixes this-> ![image](https://user-images.githubusercontent.com/3048593/54977359-0efa1c00-4fc3-11e9-90bd-b00c9f973d13.png)
> PMM-3716 Fixing Issue with AWS Staging PMM2.0

- password-page/package-lock.json
https://jira.percona.com/browse/PMM-4337
> PMM-4337 Update lodash

- password-page/package-lock.json
https://jira.percona.com/browse/PMM-4337
> PMM-4337 Update lodash.mergewith

- supervisord.conf
https://github.com/Percona-Lab/pmm-submodules/pull/394
> PMM-4550 Update PG to PG11 inside PMMserver

- sysconfig/grafana-server
- sysconfig/node_exporter
- sysconfig/pmm-manage
- sysconfig/prometheus
- tmpfiles.d-pmm.conf
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-446/8/
> PMM-4353 Remove systemd remnants

- installation-wizard-page/src/App.jsx
https://github.com/Percona-Lab/pmm-submodules/pull/590
> PMM-5201 Add correct doc link.

- import-dashboards.py
> PMM-5104 Remove CloudWatch Grafana datasource remnants

- entrypoint.sh
https://jira.percona.com/browse/PMM-4931
FB:  https://github.com/Percona-Lab/pmm-submodules/pull/684
Related PRs:
- https://github.com/percona/pmm-server-packaging/pull/112
- https://github.com/percona/pmm-server/pull/192
- https://github.com/percona/pmm-managed/pull/341
- https://github.com/percona/qan-api2/pull/81
> PMM-4931 Add Environment variables validator.

- import-dashboards.py
Reverts percona/pmm-server#197
> Revert "PMM-5547 Change http method for prometheus"

- import-dashboards.py
> PMM-5581 investigate possibility of updating Grafana plugins

- installation-wizard-page/package.json
Note: this was preventing the static resources from being properly loaded
> PMM-5700 restore the link to homepage

- password-page/package-lock.json
- password-page/package.json
> PMM-5699 bump up minimist

- nginx.conf
Increasted `client_max_body_size` to 10MB in **nginx.conf**
> PMM-5682 increased client_max_body_size

- nginx.conf
> PMM-5891 add news panel to pmm home page

- import-dashboards.py
> PMM-5706 Installed Grafana plugins are removed after upgrade

- nginx.conf
Fixed redirects for `/password-page`
> PMM-5813 fixed redirects

- nginx.conf
Updated **nginx.conf** to block CVE-2020-13379
> PMM-6086 CVE-2020-13379 (PMM1)

- import-dashboards.py
> PMM-6230 Keep changes in Home Dashboard during the updates

- import-dashboards.py
Adds PT Summary datasource to import script
https://github.com/Percona-Lab/pmm-submodules/pull/1065
> PMM-3831 PT Summary

- nginx.conf
> PMM-6495 User account Forgot your password gives Unauthorized error

- nginx.conf
Adds missing "graph" to the URL when opening explore in new tab.
https://github.com/Percona-Lab/pmm-submodules/pull/1103
> PMM-6535 Rule to add graph to explore url

- import-dashboards.py
- nginx.conf
> PMM-6489 include additional grafana plugin to pmm2

- import-dashboards.py
> PMM-6645 Issue with vertamedia-clickhouse-datasource plugin

- import-dashboards.py
> PMM-6518 Dashboards datasource name change

- nginx.conf
- supervisord.conf
adds vmalert path replace for prometheus api,
changes victoriametrics path,
changes pmm-managed flags
> PMM-6403 update nginx & supervisor config files for VM integration

- nginx.conf
- supervisord.conf
Reverts percona/pmm-server#235
> Revert "PMM-6403 update nginx & supervisor config files for VM integration"

- nginx.conf
- supervisord.conf
Reverts percona/pmm-server#237
> Revert "Revert "PMM-6403 update nginx & supervisor config files for VM integration""

- nginx.conf
> PMM-5137 fix swagger accessibility

- entrypoint.sh
- import-dashboards.py
Reverts percona/pmm-server#240
> Revert "PMM-7085 DBaaS dashboard showing when feature flag not enabled"

- nginx.conf
FB https://github.com/Percona-Lab/pmm-submodules/pull/1403
> PMM-6766 remove-qan-app

- import-dashboards.py
> PMM-7472 Remove Prometheus datasource

- rhel/SPECS/pmm-update.spec
> Changes from 2.16

- rhel/SPECS/alertmanager.spec
https://jira.percona.com/browse/PMM-7302
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1736
> PMM-7302 Upgrade alertmanager to 0.21

- rhel/SPECS/pmm-update.spec
> Changes from 2.17.0

- nginx.conf
https://jira.percona.com/browse/PMM-8213
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1834
> PMM-8213 Fix news panel

- rhel/SPECS/victoriametrics.spec
> PMM-7584 Update VictoriaMetrics 1.53.1 to 1.60.0

- supervisord.conf
https://github.com/Percona-Lab/pmm-submodules/pull/1895
> PMM-8350 fix pmm-update. Revert change pmm-update supervisor config

- rhel/SPECS/grafana.spec
https://github.com/Percona-Lab/pmm-submodules/pull/1840
> PMM-7809 upgrade grafana spec

- import-dashboards.py
Here are used two initial commits from 
https://github.com/percona/pmm-server/pull/248
The initial PR is broken after rebase
> PMM-7410 use grafana api for operations with folders

- rhel/SPECS/pmm-update.spec
> Changes from 2.20.0

- import-dashboards.py
> PMM-8703 Update to 2.21 broke at custom dashboard

- import-dashboards.py
> PMM-8767 Copied dashboards with tags ended up in unexpected folder 

- rhel/SPECS/grafana.spec
https://jira.percona.com/browse/PMM-8967
> PMM-8967 Update grafana version to 7.5.11

- import-dashboards.py
See also https://github.com/percona/pmm-update/pull/158
> PMM-9061 migrate provisioning to internal grafana mechanism

- packer/ansible/agent.yml
- packer/ansible/files/daemon.json
I added Docker config to agents and updated docker-compose and kubectl
> PMM-7 add docker config

- packer/agent.pkr.hcl
- packer/ansible/agent.yml
I added the ARM64 agent type for Jenkins.
> PMM-7 Add ARM64 workers support to Jenkins

- rhel/SPECS/victoriametrics.spec
PMM-9306 update victoria metrics to 1.72.0 version.
> PMM-9306 Upgrade VictoriaMetrics to 1.72.0 release

- Makefile
- packer/ansible/agent.yml
1. Added wget to our Jenkins agent
2. Upgrade packer to the latest version
> PMM-7 add wget to agent and upgrade packer

- rhel/SPECS/grafana.spec
We forgot to change version of our Grafana package
> PMM-7 up grafana version

- rhel/SPECS/victoriametrics.spec
PMM-9780 Upgrade VictoriaMetrics version for 1.76.0.
> PMM-9780 Upgrade VictoriaMetrics for 1.76.0 version

- .github/pull_request_template.md
- rhel/SPECS/victoriametrics.spec
PMM-9999
Build: SUBMODULES-2518
> PMM-9999 upgrade victoriametrics to 1.77.1

- ansible/roles/pmm2-images/tasks/main.yml
- rhel/SPECS/alertmanager.spec
- rhel/SPECS/dbaas-controller.spec
- rhel/SPECS/dbaas-tools.spec
- rhel/SPECS/grafana.spec
- rhel/SPECS/percona-dashboards.spec
- rhel/SPECS/percona-qan-api2.spec
- rhel/SPECS/pmm-server.spec
- rhel/SPECS/pmm-update.spec
> PMM-10027 remove useless packages

- Makefile
> PMM-7 fix npm install

- rhel/SPECS/pmm-managed.spec
[PMM-10206](https://jira.percona.com/browse/PMM-10206)
Change repository path with pmm-manage to monorepo.
TO DO:
After merging should change %global commit in pmm-managed.spec to actual commit.
> PMM-10206 Change repo for pmm-managed to pmm monorepo.

- rhel/SPECS/pmm-managed.spec
> fix pmm-managed release version

- rhel/SPECS/pmm-managed.spec
> PMM-7 fix pmm-managed pacakge

- rhel/SPECS/pmm-update.spec
The current pmm-update package is broken and has bigger revision than new packages.
PMM-10227
Build: SUBMODULES-0
> PMM-10227 up pmm-update revision

- rhel/SPECS/grafana.spec
> PMM-7 fix Grafana package version
